# https://ngrok.com/docs/using-ngrok-with/docker/compose#using-ngrok-with-docker-compose
services:
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--url=${NGROK_URL}"
      - "host.docker.internal:11434"
      # Expose Ollama to the network in Ollama settings
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
